---

- name: Configure Grafana Loki
  hosts: default
  become: true
  tasks:
    - name: Allow SSH traffic
      community.general.ufw:
        rule: allow
        name: OpenSSH
        state: enabled

  roles:
    - role: prvsn_docker
    - role: prvsn_promtail
    - role: prvsn_node_exporter
      prvsn_node_exporter_internal_network_cidr: "{{ internal_network_cidr }}"
    - role: prvsn_loki
      prvsn_loki_internal_network_cidr: "{{ internal_network_cidr }}"
    - role: prvsn_prometheus
      prvsn_prometheus_internal_network_cidr: "{{ internal_network_cidr }}"
    - role: prvsn_grafana_oss
      prvsn_grafana_oss_internal_network_cidr: "{{ internal_network_cidr }}"
