version: "3"

services:
  grafana:
    image: grafana/grafana:10.0.3
    volumes:
      - grafana_data:/var/lib/grafana
      - ./files/dashboards:/etc/grafana/provisioning/dashboards
      - ./files/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      start_period: 15s
      interval: 2s
      retries: 10

volumes:
  grafana_data:
