---

- name: Install promtail .deb package
  ansible.builtin.apt:
    deb: "{{ prvsn_promtail_download_url }}"

- name: Get available groups
  ansible.builtin.getent:
    database: group

- name: Add promtail user to adm group
  ansible.builtin.user:
    name: promtail
    groups: adm
    append: true
  when: "'adm' in ansible_facts.getent_group"

- name: Add promtail user to root group
  ansible.builtin.user:
    name: promtail
    groups: root
    append: true
  when: "'root' in ansible_facts.getent_group"

- name: Add promtail user to systemd-journal group
  ansible.builtin.user:
    name: promtail
    groups: systemd-journal
    append: true
  when: "'systemd-journal' in ansible_facts.getent_group"

- name: Add promtail user to docker group
  ansible.builtin.user:
    name: promtail
    groups: docker
    append: true
  when: "'docker' in ansible_facts.getent_group"

- name: Confgure promtail
  ansible.builtin.template:
    src: promtail.config.yml.j2
    dest: /etc/promtail/config.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart promtail
