---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: false
    uid: 3c8a6fc9-f46a-441c-88b7-98201f5e3ba2

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: 0283bfaf-caae-4a6b-9daf-761911454d55
