---

- name: Install loki .deb package
  ansible.builtin.apt:
    deb: "{{ _prvsn_loki_download_url }}"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Allow port 3100
  ansible.posix.firewalld:
    port: 3100/tcp
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  when: "'firewalld' in ansible_facts.packages"

- name: Allow port 9096
  ansible.posix.firewalld:
    port: 9096/tcp
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  when: "'firewalld' in ansible_facts.packages"
