---

- name: Install firewalld package
  ansible.builtin.package:
    name: firewalld
    update_cache: true
    state: present

- name: First attached network
  ansible.builtin.set_fact:
    first_attached_network: "{{ ansible_interfaces | difference(['lo', 'eth0']) | first }}"

- name: Configure internal zone
  ansible.posix.firewalld:
    interface: "{{ first_attached_network }}"
    zone: internal
    permanent: true
    state: enabled

- name: Get default zone
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      firewall-cmd --get-default-zone
  changed_when: false
  register: default_zone

- name: Set internal as default
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      firewall-cmd --set-default-zone=internal
  when: default_zone.stdout != 'internal'
  changed_when: default_zone.stdout != 'internal'
  notify: Restart firewalld
