version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.46.0
    restart: unless-stopped
    entrypoint: "run_prometheus"
    volumes:
      - ./scripts/prometheus:/usr/local/bin
      - prometheus_targets:/etc/prometheus/targets
      - ./files/prometheus.yml:/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    environment:
      - HCLOUD_READ_TOKEN
      - HCLOUD_NETWORK_NAME
    healthcheck:
      test: [
        "CMD-SHELL", "wget -q --spider localhost:9090/-/healthy && echo 'healthy'",
        "CMD-SHELL", "wget -q --spider localhost:9090/-/ready && echo 'ready'",
        ]
      start_period: 15s
      interval: 2s
      retries: 10
    expose:
      - 9090

  hcloud_load_balancer_exporter:
    build:
      context: hcloud_load_balancer_exporter
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: hcloud_load_balancer_exporter
    expose:
      - 8000
    environment:
      LOAD_BALANCER_IDS: "all"
      ACCESS_TOKEN: "${HCLOUD_READ_TOKEN}"
      SCRAPE_INTERVAL: 30
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8000 && echo 'ready'"]
      start_period: 20s
      interval: 2s
      retries: 10

volumes:
  prometheus_data:
  prometheus_targets:
