---

- name: Install node_exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: 1.6.1

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Allow port 9100
  ansible.posix.firewalld:
    port: 9100/tcp
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  when: "'firewalld' in ansible_facts.packages"
