---

- name: Install node_exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: 1.6.1

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Allow all access from internal network to port 9100
  community.general.ufw:
    rule: allow
    to_port: "9100"
    proto: tcp
    from_ip: "{{ prvsn_node_exporter_internal_network_cidr }}"
    state: enabled
