---

- name: Install loki .deb package
  ansible.builtin.apt:
    deb: "{{ _prvsn_loki_download_url }}"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Allow all access from internal network to port 3100
  community.general.ufw:
    rule: allow
    to_port: "3100"
    proto: tcp
    from_ip: "{{ prvsn_loki_internal_network_cidr }}"
    state: enabled

- name: Allow all access from internal network to port 9096
  community.general.ufw:
    rule: allow
    to_port: "9096"
    proto: tcp
    from_ip: "{{ prvsn_loki_internal_network_cidr }}"
    state: enabled
