#!/bin/bash

cd packer/base_server || exit

packer build \
  -var "network_name=eu-central-test" \
  -var "environment=test" \
  -var "loki_server_ip=10.1.1.2" \
  -var "internal_network_cidr=10.1.0.0/16" \
  base_server.pkr.hcl

packer build \
  -var "network_name=us-east-test" \
  -var "environment=test" \
  -var "loki_server_ip=10.2.1.2" \
  -var "internal_network_cidr=10.2.0.0/16" \
  base_server.pkr.hcl

packer build \
  -var "network_name=us-west-test" \
  -var "environment=test" \
  -var "loki_server_ip=10.3.1.2" \
  -var "internal_network_cidr=10.3.0.0/16" \
  base_server.pkr.hcl

cd ../../ || exit

cd packer/grafana || exit

packer build \
  -var "network_name=eu-central-test" \
  -var "loki_server_ip=10.1.1.2" \
  -var "hcloud_read_token=abcde" \
  -var "prometheus_network_name=eu_central_test" \
  -var "internal_network_cidr=10.1.0.0/16" \
  -var "environment=test" \
  grafana.pkr.hcl

packer build \
  -var "network_name=us-east-test" \
  -var "loki_server_ip=10.2.1.2" \
  -var "hcloud_read_token=abcde" \
  -var "prometheus_network_name=us_east_test" \
  -var "internal_network_cidr=10.2.0.0/16" \
  -var "environment=test" \
  grafana.pkr.hcl

packer build \
  -var "network_name=us-west-test" \
  -var "loki_server_ip=10.3.1.2" \
  -var "hcloud_read_token=abcde" \
  -var "prometheus_network_name=us_west_test" \
  -var "internal_network_cidr=10.3.0.0/16" \
  -var "environment=test" \
  grafana.pkr.hcl
