version: "3"

services:
  loki:
    image: grafana/loki:2.8.0
    volumes:
      - ./files/config.yaml:/etc/loki/config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider localhost:3100/ready" ]
      start_period: 15s
      interval: 5s
      retries: 10

volumes:
  loki_data:




