galaxy_info:
  role_name: prvsn_internal_network_firewall
  author: Marcos Essindi
  description: Configures the internal network firewall
  issue_tracker_url: https://github.com/dunkelbraun/prvsn-ansible-roles

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags: []

dependencies: []
