#!/usr/bin/env ruby

require "json"
require "net/http"
require "uri"
require "open3"

SERVERS_URI = URI.parse("https://api.hetzner.cloud/v1/servers").freeze
AUTH_HEADER = { Authorization: "Bearer #{ENV["HCLOUD_READ_TOKEN"]}" }.freeze

response = Net::HTTP.get(SERVERS_URI, AUTH_HEADER)
json_response = JSON.parse(response, symbolize_names: true)

server_ips = json_response.fetch(:servers, []).map do |server|
  server.fetch(:private_net, [{}]).first.fetch(:ip, nil)
end.compact

PORTS = {
  "9104" => :mysql,
  "9121" => :redis,
  "9114" => :elastic_search,
  "9187" => :postgres,
  "9127" => :pgbouncer
}.freeze

File.open("/etc/prometheus/targets/file_service_discoverer.yml", "w") do |file|
  PORTS.each do |port, service|
    available_servers = server_ips.collect do |ip|
      command = "timeout 1 nc -zv #{ip} #{port}"
      _, status = Open3.capture2e(command)
      status.success? ? "#{ip}:#{port}" : nil
    end.compact

    next if available_servers.none?

    file.puts <<~LINE
      - targets: #{available_servers.to_json}
        labels:
          job: "#{service}"
    LINE
  end
end
