{
 "title": "Load Balancers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(hetzner_load_balancer_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Target Health",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hetzner_load_balancer_service_state{hetzner_load_balancer_name=\"$loadbalancer\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hetzner_load_balancer_open_connections{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "hetzner_load_balancer_bandwidth_in{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}in"
    },
    {
     "expr": "hetzner_load_balancer_bandwidth_out{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}out"
    }
   ]
  },
  {
   "title": "Connections per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hetzner_load_balancer_connections_per_second{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }} cps"
    }
   ]
  }
 ]
}